### ISSUE TITLE
Modal component is still rendered (although transparent) after closed by clicking on overlay

### ISSUE THREAD

**Issue by reaktivo** [Travix-International/travix-ui-kit#109]
When I create a Modal component in the following way:

```js
<Button size="s" onClick={() => setState({ isOpenNormalModal: true })}>Open normal modal</Button>
<Modal active={state.isOpenNormalModal}>
  Modal Content
</Modal>
```

I would expect that clicking on the background overlay would hide the modal and allow the page to be clicked/scrolled as normal. If the `onClose` prop is not set to a function that sets the `active` prop, the background overlay becomes transparent, but still clickable, and prevents normal interaction with the page.

I tried a few possible fixes, but those introduced other buggy behaviour.

![buggy_modal](https://user-images.githubusercontent.com/13637/27542400-70a8ed2e-5a87-11e7-942e-62a1b6476853.gif)

**Comment by asci** [comment]
would
```css
.hidden .background {
pointer-event: none;
}
```

fix this?

**Comment by reaktivo** [comment]
Nope, the problem is that the Modal is still being rendered and while rendered it prevents the page from being scrolled.
