### ISSUE TITLE
Import PropTypes from `prop-types` package only

### ISSUE THREAD

**Issue by fahad19** [Travix-International/travix-ui-kit#135]
To make it easier for us to upgrade to React v15+, please import PropTypes from `prop-types` package only, not `react`.

```js
// good
import PropTypes from 'prop-types';

// bad
import { PropTypes } from 'react';
```

I see multiple components that need updating: https://github.com/Travix-International/travix-ui-kit/search?utf8=%E2%9C%93&q=PropTypes&type=

**Comment by asci** [comment]
I guess we need to apply [codemod](https://github.com/reactjs/react-codemod#react-proptypes-to-prop-types) here and add some rules
