### ISSUE TITLE
Content inside the panel not scrollable

### ISSUE THREAD

**Issue by AlleeX** [Travix-International/travix-ui-kit#141]
content inside panel not scrollable

![selection_497](https://user-images.githubusercontent.com/10462372/29213556-5dfaf99e-7eac-11e7-9624-bb0359fb8bb4.png)

**Comment by yurist38** [comment]
Should we make it scrollable only for content block and keep header fixed?

**Comment by AlleeX** [comment]
Will be cool to have fixed header (optional) and scrollable content inside body

**Comment by yurist38** [comment]
Agree, we should be able to specify that.
