### ISSUE TITLE
Side panel (close button doesn't work). js error in safari 9.1

### ISSUE THREAD

**Issue by AlleeX** [Travix-International/travix-ui-kit#192]
# Browsers and versions affected

safari 9.1

# Description

Side panel (close button doesn't work). js error in safari 9.1

![selection_112](https://user-images.githubusercontent.com/10462372/31011011-7f747214-a515-11e7-9a0e-d514816982f7.png)

**Comment by froskie** [comment]
Fixed with https://github.com/Travix-International/travix-ui-kit/pull/197
