### ISSUE TITLE
Refactor List component to get rid of renderEmptyItems attr

### ISSUE THREAD

**Issue by yurist38** [Travix-International/travix-ui-kit#215]
We merged #213 recently but the question (do we really need that prop?) is still open. Most probably we can completely remove it and just do not render empty items for all cases. If you know any case when you need to render empty item(s) within the `List` component please add your comment here. Otherwise, we have to refactor that functionality later on.

**Comment by iwwwi** [comment]
I vote for not rendering the empty items ;)

**Comment by spzm** [comment]
As I understand correctly, in case I need (for some reason) empty items behavior I can put just space strings `' '`.

From the code perspective, empty items filtering can be always done outside the List. But minimal filtering on empty values looks ok for me.

**Comment by yurist38** [comment]
@spzm 
1) Yes, `' '` one space string will be rendered.
2) You're right, most of the times it's possible and more correct to make a filtering outside. Why I did that change in `<List />` is because I had a case with labels. That was a pain to filter out empty labels.

**Comment by spzm** [comment]
@yurist38 I like case you described. I also vote for not rendering empty items (removing prop as well). The list that renders empty items looks weird in real life. If someone need 'empty behavior' - empty ReactElement or string with space can be used.
