### ISSUE TITLE
Branding (logo and name)

### ISSUE THREAD

**Issue by asci** [Travix-International/travix-ui-kit#216]
Hello everyone!

It is already a year since we started active development of UI kit project. I guess it is time to find a proper name and a new logo. That would be the first step to build Travix Styleguide platform.

We already have a permission to open source our themes, so later we can add an interface to the UI kit website and we'll have a real showcase for all the brands. 

We can also add some general information about our brands, color palettes, fonts, used resources, icon sets, etc. 

And this would be really good under another specific Travix technical brand.

I'm not a designer, but I have few ideas and variations. 

For the brand name I have 2 ideas:

![uni](https://user-images.githubusercontent.com/778908/32245350-cb9b7730-be7b-11e7-9161-d1c50a10f3b9.png)
![inv](https://user-images.githubusercontent.com/778908/32245352-ce0448da-be7b-11e7-9eb0-0f136f9835b1.png)

"Uniblocks" — universal blocks to build Travix web applications
"Inventory" — our inventory where we have all the items to build Travix web applications

Fonts: Quicksand or Fira Sans, both available on Google Fonts

The logos are more-less the same, based on the idea of composable squares. (the last one uses our brand colors, just warm ones)

Where do I plan to use brand:
- Styleguide platform
- Slides for presentations
- List of Travix open source projects
...

Any feedback is desirable. If you have an alternative idea don't hesitate to post it as well. You can also vote for the combination you like more with emoji number.

Thanks!

**Comment by fahad19** [comment]
once decided on a name, please consider reserving them quickly on:

* GitHub (org)
* Twitter
* npm (org / package)
* Dribbble

**Comment by leandrooriente** [comment]
Great work @asci 

I liked the pink Uniblocks

**Comment by spzm** [comment]
I vote for Uniblocks as well

Thanks @asci!

**Comment by RumataDeEstor** [comment]
I vote for Uniblocks with green-blue squares.

**Comment by JutIgor** [comment]
Uniblocks (first variant) looks good and modern :)

**Comment by iwwwi** [comment]
How about involving our designing team in this discussion? :)

**Comment by asci** [comment]
@iwwwi feedback from the design team:
>Don't create a new logo, use Travix logo instead

**Comment by iwwwi** [comment]
Here is the feedback that I got today :) 
Let's focus on completing the kit at least to 1st stable version... 🎉 

![screen shot 2017-11-03 at 17 15 28](https://user-images.githubusercontent.com/5980657/32384271-a7529e08-c0ba-11e7-80e0-3bfb50419839.png)
