### ISSUE TITLE
Bug: GH-pages broken link "back" in isolated mode

### ISSUE THREAD

**Issue by ilabacheuski** [Travix-International/travix-ui-kit#233]
# Browsers and versions affected
any

# Description
The bug concerns gh-pages. The link "Back" in Isolated view mode is wrong

# Steps to reproduce

For example for Button description. When you click "Open isolated" link it will open in isolated content. After that just click the link "Back" and you will get 404 because the link miss /travix-ui-kit/ ending.

# Expected results

Going back to previous page

# Actual results

404 page

![spectacle x20414](https://user-images.githubusercontent.com/10571879/32880038-4cd6359a-cabd-11e7-960f-fa66da800bed.jpg)

**Comment by mAiNiNfEcTiOn** [comment]
PR #236 fixes this.
