### ISSUE TITLE
Bug: GH-Pages - Show code button does not work

### ISSUE THREAD

**Issue by ilabacheuski** [Travix-International/travix-ui-kit#234]
![recording 3](https://user-images.githubusercontent.com/10571879/32880671-8d027960-cabf-11e7-93ec-385a8774de43.gif)
# Browsers and versions affected

any or at least chrome

# Description

clicking "Show code" button-link does not work. In console there is an error:
`TypeError: Cannot read property 'any' of undefined`

# Steps to reproduce

Go to gh-pages, click "show code"

# Expected results

show the correspondent source code

# Actual results

Element is not opening.

**Comment by yurist38** [comment]
It should be fixed once we have `react-styleguidist` updated to latest version. Just checked on my local. I will create a PR soon.
