### ISSUE TITLE
Upgrade Travis node version to 8

### ISSUE THREAD

**Issue by yurist38** [Travix-International/travix-ui-kit#237]
# Browsers and versions affected

> All browsers

# Description

> Since we are upgrading all projects to use Node.js v8 it makes sense to keep `ui-kit` pipeline also up to date. I tried to upgrade, but Travis build was not passed. So need to find the problem and upgrade Node.js version.

# Steps to reproduce

> * Change Node version in `./.travis.yml` file to `8`
> * Push branch
> * Travis' build should be failed.

# Expected results

> Passed all pipelines on PR with `Node.js` v8 in Travis.

**Comment by leandrooriente** [comment]
Closed: https://github.com/Travix-International/travix-ui-kit/pull/348
