### ISSUE TITLE
[slidingPanel] Refactor width prop to do not use inline styling

### ISSUE THREAD

**Issue by yurist38** [Travix-International/travix-ui-kit#240]
# Browsers and versions affected

> All

# Description

> Currently `width` prop in `slidingPanel` component is being used in inline styles and should be refactored. We could use prop `size` with variations `s` (480px) and `m` (720px) instead. Seems like only those 2 sizes we use currently.
> AFAIK `width` prop was used only in `hotels` widget. So this refactoring must be aligned with hotels team.

# Expected results

> The new prop must have a default value (most probably `s`) and be not required. Width must be defined in CSS, not inline.

If you know any other cases where `width` prop was used, please let us know.

**Comment by mAiNiNfEcTiOn** [comment]
PR #235 fixes this.
