### ISSUE TITLE
GH-pages: Link's labels are unreadable

### ISSUE THREAD

**Issue by ilabacheuski** [Travix-International/travix-ui-kit#246]
# Browsers and versions affected

any, at least chrome

# Description

Looks like after #236 link's labels like "Open isolated" or "Show code" are not shown. Instead you can see just ugly squares

# Steps to reproduce

[https://travix-international.github.io/travix-ui-kit/](https://travix-international.github.io/travix-ui-kit/)

# Expected results

Readable text for links

# Actual results

![screenshot from 2017-11-23 15-24-09](https://user-images.githubusercontent.com/10571879/33177476-fa6f1640-d062-11e7-8480-f6a1076fdf0f.png)

**Comment by yurist38** [comment]
So yeah, it's not a bug but feature 😄  We could investigate maybe 6th version allows to configure it somehow...

**Comment by spzm** [comment]
Unfortunately, React styleguide [doesn't support ](https://github.com/styleguidist/react-styleguidist/blob/c001dd5b45a5632e1e24f925cff2a073ce618ff2/src/rsg-components/slots/IsolateButton.js#L11) any configuration of this button.

When mouse pointer is hover it will show title 'Show all components'. New version - new UX :)

**Comment by ilabacheuski** [comment]
In the page it is completely unclear what does it mean :-1:

**Comment by yurist38** [comment]
I agree with you @ilabacheuski about `Open isolated` is not very clear until you tried to click on it, but there is no simple way to change that now. We could create an issue (PR) for changing it in https://github.com/styleguidist/react-styleguidist as an option.
