### ISSUE TITLE
Fix overflow for Modal in IE11

### ISSUE THREAD

**Issue by yurist38** [Travix-International/travix-ui-kit#296]
# Browsers and versions affected

> Our lovely IE11

# Description

> There is an issue with overflow content in Modal component

<img width="592" alt="screen shot 2017-12-27 at 10 52 16" src="https://user-images.githubusercontent.com/10692413/34378218-17aac19e-eaf5-11e7-9e10-088c2229c468.png">

# Steps to reproduce

> Open ui-kit site in IE11 and navigate to Modal component. Then click on `Open Custom Modal` button. You will see that it behaves differently compare to other browsers (bottom part of modalbox went below the screen).

# Expected results

> Same behavior as in other browsers - you should be able to see the whole modalbox and its central (content) part should be scrollable.

**Comment by leandrooriente** [comment]
Closed https://github.com/Travix-International/travix-ui-kit/pull/347
