### ISSUE TITLE
Fix styleguidist code preview button for accp

### ISSUE THREAD

**Issue by yurist38** [Travix-International/travix-ui-kit#300]
# Browsers and versions affected

> All browsers

# Description

> I've just noticed that code preview button doesn't work on accp websites auto-deployed by Travis only (but it works fine on production, localhost and even when you deploy accp manually running `npm run deploy:accp`).
On accp deployed by Travis when you click `CODE` below the rendered component It returns an error:
![screen shot 2017-12-27 at 15 29 04](https://user-images.githubusercontent.com/10692413/34384236-455095f8-eb1b-11e7-9d03-af3a834d62f4.png)

# Steps to reproduce

> Go to any accp deployed automatically by Travis (GitHub CI pipeline) and click `CODE` button located below every component preview

# Expected results

> Make it working 😄

**Comment by leandrooriente** [comment]
Seems to be working now.
https://fix-e-persist-on-esc-modal-wfhlemtgqg.now.sh/

Should we close?

**Comment by yurist38** [comment]
Yeah, it was fixed already. Closing.
