### ISSUE TITLE
Improve Badge component to support other positions (i.e. centered ones)

### ISSUE THREAD

**Issue by yurist38** [Travix-International/travix-ui-kit#329]
# Description

> We stuck with a case when `Badge` is centered on top. So I think Badge component should be improved to support all possible positions. I think it should support centered case on every side and corners as well for each side. Feel free to put your ideas if have any...

**Comment by iwwwi** [comment]
i guess it is enough to pass new prop `isCentered`: false|true , where the default is false for backwards compatibility. Then apply if possible generic class for centring the Badge depending on its position :)
