### ISSUE TITLE
Disable scroll of the page when do scroll over opened Modal or SlidingPanel

### ISSUE THREAD

**Issue by yurist38** [Travix-International/travix-ui-kit#331]
# Browsers and versions affected

> All

# Description

> Right now we have the behavior when you can scroll the main page when scrolling over opened Modal or SlidingPanel. I think this behavior should be changed to block scroll of the main window till modal box or panel will be closed.

**Comment by leandrooriente** [comment]
If you use global property on SlidingPanel it prevents the body scrolling.

I don't know if it works for Modal as well

**Comment by yurist38** [comment]
As I can see `global` prop is not introduced to the `Modal` component.
