### ISSUE TITLE
Allow toggleButton to receive a JSX as items property

### ISSUE THREAD

**Issue by leandrooriente** [Travix-International/travix-ui-kit#343]
# Description

Currently `toggleButton` only accepts strings as `items` property. Sometimes the designer asks for an icon or a specific part of the text in bold, so it would be super useful if we can pass JSX as props as well.

It'll also help when you and to pass a translated text using `<L10ns />` instead of use `l` function to return a string.

# Proposal

```js
<ToggleButton
  handleSelect={() => {}}
  selectedIndex={0}
  items={[
      <L10ns name={key1} />,
      <L10ns name={key1} />,
  ]}
/>

<ToggleButton
  handleSelect={() => {}}
  selectedIndex={0}
  items={[
      'Text 1',
      'Text 2',
  ]}
/>

<ToggleButton
  handleSelect={() => {}}
  selectedIndex={0}
  items={[
      <span>Hello <strong>world</strong></span>,
      <span>Bye <strong>world</strong></span>,
  ]}
/>

<ToggleButton
  handleSelect={() => {}}
  selectedIndex={0}
  items={[
      <span><img src={airplane.svg} /> Flights</span>,
      <span><img src={account.svg} /> My account</span>,
  ]}
/>
```

**Comment by yurist38** [comment]
It looks like a good improvement, especially with that fact that we don't use `raw` labels now, only wrapped with `<L10ns />` component returning JSX. So 👍 👍

**Comment by rbardini** [comment]
What do you think of moving away from props and declaring items using children components instead? Something like:

```jsx
<ToggleButton
  handleSelect={(e, selectedValue) => setState({ selectedValue })}
  selectedValue={state.selectedValue}
>
  <Item value={1}>
    {/* anything goes here */}
  </Item>
  <Item value={2}>
    {/* anything goes here */}
  </Item>
</ToggleButton>
```

This is similar to how [react-bootstrap handles checkbox/radio groups](https://react-bootstrap.github.io/components/button-group/#btn-groups-checkbox-radio), and to me it is much easier to read. Maybe too big of a change for now, but something to think about 🙂

**Comment by leandrooriente** [comment]
I like it. We could add support to both
