### ISSUE TITLE
Rendering button

### ISSUE THREAD

**Issue by ibsukru** [Travix-International/travix-ui-kit#72]
Button component is not rendering until i add onClick event
I saw this is by purpose on code but it is very much optioned

**Comment by asci** [comment]
hm.. could you please explain your use case?

**Comment by ibsukru** [comment]
Here it is,

const Button = require('travix-ui-kit').Button;
// or
import { Button } from 'travix-ui-kit';

<Button>Add value</Button>

is not rendering

**Comment by asci** [comment]
I mean why do you need button without any action?

**Comment by ibsukru** [comment]
As i said it is opinionated, 
This should be like base html button element it always renders with or without event declarations

Can you give similar examples from similar libraries, that i can check?

**Comment by asci** [comment]
I agree this is opinionated. But on the other hand, it helps to avoid mistakes, right?
I can't provide you an example, it was my decision. If it will be better to change this behavior I'll approve the PR (but I would also like to hear from other developers)

**Comment by fahad19** [comment]
`<Button>` should render with or without any `onClick` event handler. It's primary responsibility is to render a button, even if a plain one.

Think of this form example:

```js
import { Button } from 'travix-ui-kit';

function MyForm() {
  return (
    <form onSubmit={() => this.handleSubmit()}>
      <Button type="submit">Submit</Button>
    </form>
  );
}
```

**Comment by asci** [comment]
@fahad19 as far as I can see
https://github.com/Travix-International/travix-ui-kit/blob/master/components/button/button.js#L34 
your case is covered. Any another case when you need a button (not a reset and not a submit) without `onClick`?

**Comment by fahad19** [comment]
Like I said before:

> `<Button>` should render with or without any `onClick` event handler. It's primary responsibility is to render a button, even if a plain one.

Better stay close to the HTML element that you are trying to wrap with this Component.

* Extending the behavior of `<button>` HTML element: 👍 
* Limiting the usage of regular `<button>`: 👎 

---

one other thing I noticed, why does one returned `<button>` has `...restProps`, and the other doesn't? 

https://github.com/Travix-International/travix-ui-kit/blob/92edfa8d6d9be2e0d3f3ab190456c9fe44a86e52/components/button/button.js#L36-L46

**Comment by asci** [comment]
Thanks for the interesting input, @fahad19! Unfortunately, I still can't find any proper use case for button without a handler:( 

In my humble opinion the idea of UI-kit is not being close to HTML elements, but provide right tools for right tasks. If you need a button without handler you still can use a button from HTML elements, not from UI-kit.

But as I mentioned before: I'll approve PR with a fix for this issue.

---

about `restProps` — it is a valid issue, will take care about, thanks!

**Comment by reaktivo** [comment]
My 2 cents on this issue, is that from a developer point of view, it seems expected for a component that represents a HTMLElement to behave the same way, when no added API is being used (e.g mods, variation, etc).

**Comment by yurist38** [comment]
Hi, guys! I've stuck with the same problem. My use case is a close button for `SlidingPanel`. We no need any `onClick` handler in that case, we just add `rel="close"` attribute (or `data-rel="close"` after [this PR](https://github.com/Travix-International/travix-ui-kit/pull/146) is merged). So let's get rid of that logic and render button anyway! I'll create PR for that.

**Comment by asci** [comment]
@yurist38 but you're not using Button component there, right?

**Comment by yurist38** [comment]
Not in UI-KIT codebase, I use <Button /> in new Seatmap widget, inside SlidingPanel's children.
