### ISSUE TITLE
Button variations is not working

### ISSUE THREAD

**Issue by ibsukru** [Travix-International/travix-ui-kit#73]
https://travix-international.github.io/travix-ui-kit/ Have tried ghost, rounded .. but no success

**Comment by asci** [comment]
They are not implemented yet (:

**Comment by ibsukru** [comment]
Oki, Better to update documentation, we were pointing our integration with ui kit tasks based on this features, it is misleading.

**Comment by yurist38** [comment]
@ibsukru should we close this issue now or it's still relevant?
