### ISSUE TITLE
NPM package without unnecessary `dependencies`

### ISSUE THREAD

**Issue by fahad19** [Travix-International/travix-ui-kit#88]
## Current situation

As a developer, I expect to use `travix-ui-kit` by just installing it. No bundling should be required.

But the current situation demands that we can make our bundles by injecting SASS variables, so there's a direct dependency on Webpack.

## What we can improve

But we can consider removing Babel and some testing libraries as a direct dependency, if we follow a slightly different structure.

When we put things in `dependencies`, all of them get installed in our application using `travix-ui-kit`. But we don't need all of them in our application consuming the ui-kit, and can be moved to `devDependencies` so only ui-kit maintainers get to use them when developing this project in this repo.

## Packages that can be moved from `dependencies` to `devDependencies`

* `babel-cli`
* `babel-core`
* `babel-eslint`
* `babel-jest`
* `babel-loader`
* `babel-preset-travix`
* `babel-register`

And also move these to `devDependencies` and treat them as peer dependencies (meaning, developers should install them manually themselves), like @mAiNiNfEcTiOn mentioned:

* `react`
* `react-dom`

## Directory structure

```
├── src/ (ES6/Babel - contained in the repo)
      ├── components/
      │   ├── Button.js
      ├── index.js
├── lib/ (transpiled ES5 - not contained in the repo, but published to npm)
      ├── components/
      │   ├── Button.js
      ├── index.js
├── index.js
└── package.json
```

## Root `index.js`

```js
// index.js
module.exports = require('./lib');
```

## `prepublish`

As a `prepublish` process, you can prepare the `lib` directory by transpiling `src` with Babel. So we don't need to have Babel with the right presets or anything for consuming `travix-ui-kit` in our applications.

**Comment by mAiNiNfEcTiOn** [comment]
I agree with that, however I have a few remarks:

* I am going to add a `prepare` task for future-proof implementation: https://iamakulov.com/notes/npm-4-prepublish/
* I'd then like to release a _major_ version of the kit since we're breaking completely the existing implementation (dropping the builder and relying in css-variables).

What do you think, folks?

@Travix-International/frontend @EduardTrutsyk @AlleeX @spzm @RumataDeEstor

**Comment by mAiNiNfEcTiOn** [comment]
Hmmm, now that I have read properly the issue, I'd reduce this for a minor, if we maintain the builder, making it the same behaviour, but transpiled.

**Comment by fahad19** [comment]
:)

**Comment by fahad19** [comment]
I think this Issue can be closed? I see latest master's package.json has only one item in `dependencies`. So it's already done.

**Comment by mAiNiNfEcTiOn** [comment]
Closing. Thanks @fahad19
